[wildrift-news-en-us]
title = "Wild Rift News (en-us)"
url = "https://wildrift.leagueoflegends.com/en-us/news/"
entrySelector = "a[data-testid='articlefeaturedcard-component']"
titleSelector = "div[data-testid='card-title']"
linkSelector = "*"
dateSelector = "div[data-testid='card-date'] > time"
waitUntil = "load"

[wildrift-news-zh-tw]
title = "Wild Rift News (zh-tw)"
url = "https://wildrift.leagueoflegends.com/zh-tw/news/"
entrySelector = "a[data-testid='articlefeaturedcard-component']"
titleSelector = "div[data-testid='card-title']"
linkSelector = "*"
dateSelector = "div[data-testid='card-date'] > time"
waitUntil = "load"
